version: '2'
networks:
  basic:
services:

  ca.kit.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.kit.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.genome-platform.kit.com-cert.pem
      # TODO replace following path with generated filename
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/7fecb284d0ce1001f47d333e69d2cf70cec0e59fb5166c2a3fcf100c3af01214_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw' -d
    volumes:
      - ./crypto-config/peerOrganizations/genome-platform.kit.com/ca/:/etc/hyperledger/fabric-ca-server-config
    extra_hosts:
      - "peer0.genome-platform.kit.com:193.196.37.152" # ResearchLab
      - "peer2.genome-platform.kit.com:193.196.36.153" # Hospital
    container_name: ca.kit.com
    networks:
      - basic

  peer1.genome-platform.kit.com:
    container_name: peer1.genome-platform.kit.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.genome-platform.kit.com
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=GenomePlatformMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer1.genome-platform.kit.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_basic
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    command: peer node start
    ports:
      - 8051:7051
      - 8053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/genome-platform.kit.com/peers/peer1.genome-platform.kit.com/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/genome-platform.kit.com/users:/etc/hyperledger/msp/users
        - ./config:/etc/hyperledger/configtx
#        - ./../chaincode/:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go
    extra_hosts:
    - "orderer.kit.com:193.196.37.152" # ResearchLab
    - "peer0.genome-platform.kit.com:193.196.37.152" # ResearchLab
    - "ca.kit.com:193.196.37.152" # ResearchLab
    - "peer2.genome-platform.kit.com:193.196.36.153" # Hospital
    - "ca.kit.com:193.196.36.153" # Hospital

    depends_on:
      - couchdb1
    networks:
      - basic
  couchdb1:
    container_name: couchdb1
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 6984:5984
    networks:
      - basic

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=info
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer1.genome-platform.kit.com:7051
      - CORE_PEER_LOCALMSPID=GenomePlatformMSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/genome-platform.kit.com/users/Admin@genome-platform.kit.com/msp
      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/
        - ./../network/:/opt/gopath/src/github.com/
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
    networks:
        - basic
    #depends_on:
    #  - orderer.kit.com
    #  - peer0.genome-platform.kit.com
    #  - couchdb